### PR TITLE
Bump to 3.28.1

### PR DESCRIPTION
**Pull request by josedev-union**

### CODE REVIEW

**Review by rasheedamir — DISMISSED** [review]

**Comment by stakater-user** [comment]
@josedev-union Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins-delivery.stakater.com/job/Stakater-docker/job/nexus3/job/PR-1/1/) has Failed!

**Comment by stakater-user** [comment]
@josedev-union Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins-delivery.stakater.com/job/Stakater-docker/job/nexus3/job/PR-1/2/) has Failed!

**Comment by stakater-user** [comment]
@josedev-union Yikes! You better fix it before anyone else finds out! [Build 3](https://jenkins-delivery.stakater.com/job/Stakater-docker/job/nexus3/job/PR-1/3/) has Failed!

**Comment by stakater-user** [comment]
@josedev-union Image is available for testing. `docker pull docker.io/stakater/nexus3:3.28.1-keycloak_plugin0.4.1-SNAPSHOT-PR-1-4`

**Review by rasheedamir — APPROVED** [review]

**Pull request merged**
